### ISSUE TITLE
doesn't work with tramp

### ISSUE THREAD

**Issue by samliddicott** [canatella/repo-el#6]
Seems to only work with local repo's, and not over tramp (as for example magit does)

**Comment by canatella** [comment]
Never tried it over tramp. What is the error you get ? Any log/more info would be helpful here.

**Comment by bobrofon** [comment]
It looks like [start-process](https://github.com/canatella/repo-el/blob/e504aa831bfa38ddadce293face28b3c9d9ff9b7/repo.el#L170) is trying to run `repo` locally, or at least with the wrong CWD.
As a result the following error appears in the `repo-process` buffer:
> Running repo info -lo
> error: command 'info' requires repo to be installed first.
>         Use "repo init" to install it here.
> Repo process exited abnormally with code 1

Replacing [start-process](https://www.gnu.org/software/emacs/manual/html_node/elisp/Asynchronous-Processes.html#index-start_002dprocess) with [start-file-process](https://www.gnu.org/software/emacs/manual/html_node/elisp/Asynchronous-Processes.html#index-start_002dfile_002dprocess) works for me.
